# Generated by Django 3.2 on 2022-04-12 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poster',
            old_name='category',
            new_name='motive',
        ),
    ]
