# Generated by Django 3.2 on 2022-04-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0002_rename_category_poster_motive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
