# Generated by Django 3.2 on 2022-04-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_alter_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
