# Generated by Django 3.2 on 2022-07-10 13:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_email_newslettersubscriber_news_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestposter',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
