# Generated by Django 3.2 on 2022-07-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_requestposter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestposter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
