# Generated by Django 3.2 on 2022-07-12 16:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_requestposter_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestposter',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='images'),
        ),
    ]
